name: solana_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  # bip39: ^1.0.6
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  # flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  # flutter_secure_storage: ^9.0.0
  go_router: ^13.1.0
  image: ^4.1.3
  image_picker: ^1.0.5
  solana: ^0.30.2
  solana_mobile_client: ^0.1.1+1
  solana_wallet_adapter: ^0.1.5
  solana_web3: ^0.1.3
  # web3modal_flutter: ^3.1.0-beta01

dev_dependencies:
  bloc_test: ^9.1.5
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - .env.devnet
    - lib/idl/solana_twitter.json
